BAG OF WORDS

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
import pandas as pd

In [68]:
df = pd.read_csv("data/nlp.csv", index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [69]:
import on_islem

In [70]:
df["Text_2"] = df["Text"].apply(on_islem.pre_processing)
df["Text_2"] = df["Text_2"].apply(on_islem.remove_space)
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [71]:
# boş liste kontrolü
df[df["Text_2"].str[0].isnull()]

Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...     []

In [72]:
df_index = df[df["Text_2"].str[0].isnull()].index
df = df.drop(df_index)
df = df.reset_index()
del df ["index"]

df[df["Text_2"].str[0].isnull()]

Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [73]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [74]:
df["Text_2"]

0      [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, olduğunu, iç, önemli, o...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
851                              [dogal, dil, isle, şey]
852    [ver, madencilik, doğal, dil, işle, uygulamas,...
853    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 855, dtype: object

In [75]:
df["Text_3"] = [' '.join(w for w in item) for item in df["Text_2"]]
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                            [dogal, dil, isle, şey]   
852  [ver, madencilik, doğal, dil, işle, uygulamas,...   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka olduğunu iç önemli olduk kı...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                 dogal dil isle şey  
852       ver madencilik doğal dil işle uygulamas http  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [76]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())
X

<855x4804 sparse matrix of type '<class 'numpy.int64'>'
	with 17033 stored elements in Compressed Sparse Row format>

In [77]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [78]:
df["Text_4"] = X.toarray().tolist()
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

TF-IDF

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [80]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())

In [81]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [82]:
set(X.toarray()[0])

{0.0,
 0.03508115658001388,
 0.03685011328026531,
 0.12317029281566404,
 0.1287180325367376,
 0.1293951901484212,
 0.14937145922687903,
 0.15331933006757356,
 0.15474585010773745,
 0.15623579147571884,
 0.1669097751456677,
 0.17386946496025046,
 0.1765523493830673,
 0.19014279446116142,
 0.19978536869856103,
 0.20581084119178317,
 0.21337581377665515,
 0.22232665378265135,
 0.22301838801405474,
 0.2366088330921489,
 0.3162294875300779}

In [83]:
df["Text_5"] = X.toarray().tolist()
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                            [dogal, dil, isle, şey]   
852  [ver, madencilik, doğal, dil, işle, uygulamas,...   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                 dogal dil isle şey   
852       ver madencilik doğal dil işle uygulamas http   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [84]:
len(X.toarray()[0])

4804

WORD2VEC

In [85]:
from gensim.models import Word2Vec

In [86]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [87]:
model = Word2Vec(sentences = df["Text_2"].tolist(), vector_size=100, window=5, min_count=1)
model.save("data/word2vec.model")

In [88]:
print(model)

Word2Vec<vocab=4815, vector_size=100, alpha=0.025>


In [89]:
words = list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 'yapay', 'zeka', 'il']

In [90]:
len(words)

4815

In [91]:
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                            [dogal, dil, isle, şey]   
852  [ver, madencilik, doğal, dil, işle, uygulamas,...   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                 dogal dil isle şey   
852       ver madencilik doğal dil işle uygulamas http   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [92]:
model.wv.key_to_index["yapay"]

3

In [93]:
model.wv[3]

array([-0.03720673,  0.19829895,  0.00202888, -0.05603328,  0.06706502,
       -0.31178236,  0.12055121,  0.3992345 , -0.08054531, -0.12246186,
       -0.03860046, -0.28500667, -0.07251471,  0.12556337, -0.01145025,
       -0.08734696,  0.08005503, -0.19518144, -0.01766369, -0.37888616,
        0.1675939 ,  0.05534774,  0.24530868, -0.06324458, -0.0353631 ,
        0.01333986, -0.08719078, -0.04459398, -0.15659368, -0.00637072,
        0.2010148 , -0.02247335,  0.06538938, -0.18376352, -0.04980271,
        0.17255972,  0.06465806, -0.10407612, -0.061159  , -0.31270397,
       -0.01499078, -0.25038537, -0.15012097, -0.03914012,  0.13298568,
       -0.08678872, -0.1618391 , -0.01165519,  0.0296136 ,  0.13301545,
        0.12420698, -0.2433717 , -0.09309378, -0.07038168, -0.09949535,
        0.03030346,  0.18370394, -0.08217753, -0.24729034,  0.03837648,
        0.03908882,  0.01927575,  0.00042364,  0.04390454, -0.28584352,
        0.23325361,  0.04365251,  0.16348831, -0.24421515,  0.25

In [94]:
model.wv.get_vector("yapay")

array([-0.03720673,  0.19829895,  0.00202888, -0.05603328,  0.06706502,
       -0.31178236,  0.12055121,  0.3992345 , -0.08054531, -0.12246186,
       -0.03860046, -0.28500667, -0.07251471,  0.12556337, -0.01145025,
       -0.08734696,  0.08005503, -0.19518144, -0.01766369, -0.37888616,
        0.1675939 ,  0.05534774,  0.24530868, -0.06324458, -0.0353631 ,
        0.01333986, -0.08719078, -0.04459398, -0.15659368, -0.00637072,
        0.2010148 , -0.02247335,  0.06538938, -0.18376352, -0.04980271,
        0.17255972,  0.06465806, -0.10407612, -0.061159  , -0.31270397,
       -0.01499078, -0.25038537, -0.15012097, -0.03914012,  0.13298568,
       -0.08678872, -0.1618391 , -0.01165519,  0.0296136 ,  0.13301545,
        0.12420698, -0.2433717 , -0.09309378, -0.07038168, -0.09949535,
        0.03030346,  0.18370394, -0.08217753, -0.24729034,  0.03837648,
        0.03908882,  0.01927575,  0.00042364,  0.04390454, -0.28584352,
        0.23325361,  0.04365251,  0.16348831, -0.24421515,  0.25

In [95]:
def word2vec(value):
    model = Word2Vec.load("data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)
    
    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)
        
    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [96]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [ ]:
df["Text_6"] = df["Text_2"].apply(word2vec)

In [ ]:
df.head()

In [ ]:
df["bow"] = on_islem.bag_of_words(df["Text_3"])
df["tfifd"] = on_islem.tfifd(df["Text_3"])
df["word2vec"] = df["Text_3"].apply(on_islem.word2vec)

In [ ]:
df.head()